/**
 * Auto-generated image metadata for Al Mazahir Trading Est.
 * Generated by Autonomous Asset Intelligence System
 * 
 * This file contains SEO-optimized metadata for all product images
 * including alt text, titles, descriptions, and accessibility information.
 */

export interface ImageMetadata {
  alt: string;
  title: string;
  description: string;
  keywords: string[];
  category: string;
  productName: string;
  seoFilename: string;
  dimensions: string;
  format: string;
  quality: string;
  accessibility: {
    hasAltText: boolean;
    hasTitle: boolean;
    isDescriptive: boolean;
    includesContext: boolean;
  };
}

export const imageMetadata: Record<string, ImageMetadata> = {
  "public\\assets\\safety-equipment\\safety-equipment-safety-boots-almazahir.webp": {
    "alt": "Equipment Safety Boots - Safety Equipment by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Equipment Safety Boots | Safety Equipment | Al Mazahir Trading Est.",
    "description": "High-quality equipment safety boots available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Personal protective equipment for workplace safety.",
    "keywords": [
      "Equipment Safety Boots",
      "safety",
      "protection",
      "PPE",
      "industrial safety",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "safety-equipment",
    "productName": "Equipment Safety Boots",
    "seoFilename": "safety-equipment-safety-boots-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\safety-equipment\\safety-equipment-safety-glasses-1-almazahir.webp": {
    "alt": "Equipment Safety Glasses 1 - Safety Equipment by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Equipment Safety Glasses 1 | Safety Equipment | Al Mazahir Trading Est.",
    "description": "High-quality equipment safety glasses 1 available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Personal protective equipment for workplace safety.",
    "keywords": [
      "Equipment Safety Glasses 1",
      "safety",
      "protection",
      "PPE",
      "industrial safety",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "safety-equipment",
    "productName": "Equipment Safety Glasses 1",
    "seoFilename": "safety-equipment-safety-glasses-1-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\safety-equipment\\safety-equipment-safety-glasses-almazahir.webp": {
    "alt": "Equipment Safety Glasses - Safety Equipment by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Equipment Safety Glasses | Safety Equipment | Al Mazahir Trading Est.",
    "description": "High-quality equipment safety glasses available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Personal protective equipment for workplace safety.",
    "keywords": [
      "Equipment Safety Glasses",
      "safety",
      "protection",
      "PPE",
      "industrial safety",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "safety-equipment",
    "productName": "Equipment Safety Glasses",
    "seoFilename": "safety-equipment-safety-glasses-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\safety-equipment\\safety-equipment-safety-helmet-1-almazahir.webp": {
    "alt": "Equipment Safety Helmet 1 - Safety Equipment by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Equipment Safety Helmet 1 | Safety Equipment | Al Mazahir Trading Est.",
    "description": "High-quality equipment safety helmet 1 available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Personal protective equipment for workplace safety.",
    "keywords": [
      "Equipment Safety Helmet 1",
      "safety",
      "protection",
      "PPE",
      "industrial safety",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "safety-equipment",
    "productName": "Equipment Safety Helmet 1",
    "seoFilename": "safety-equipment-safety-helmet-1-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\safety-equipment\\safety-equipment-safety-helmet-almazahir.webp": {
    "alt": "Equipment Safety Helmet - Safety Equipment by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Equipment Safety Helmet | Safety Equipment | Al Mazahir Trading Est.",
    "description": "High-quality equipment safety helmet available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Personal protective equipment for workplace safety.",
    "keywords": [
      "Equipment Safety Helmet",
      "safety",
      "protection",
      "PPE",
      "industrial safety",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "safety-equipment",
    "productName": "Equipment Safety Helmet",
    "seoFilename": "safety-equipment-safety-helmet-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\safety-equipment\\safety-equipment-work-gloves-1-almazahir.webp": {
    "alt": "Equipment Work Gloves 1 - Safety Equipment by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Equipment Work Gloves 1 | Safety Equipment | Al Mazahir Trading Est.",
    "description": "High-quality equipment work gloves 1 available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Personal protective equipment for workplace safety.",
    "keywords": [
      "Equipment Work Gloves 1",
      "safety",
      "protection",
      "PPE",
      "industrial safety",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "safety-equipment",
    "productName": "Equipment Work Gloves 1",
    "seoFilename": "safety-equipment-work-gloves-1-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\safety-equipment\\safety-equipment-work-gloves-almazahir.webp": {
    "alt": "Equipment Work Gloves - Safety Equipment by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Equipment Work Gloves | Safety Equipment | Al Mazahir Trading Est.",
    "description": "High-quality equipment work gloves available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Personal protective equipment for workplace safety.",
    "keywords": [
      "Equipment Work Gloves",
      "safety",
      "protection",
      "PPE",
      "industrial safety",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "safety-equipment",
    "productName": "Equipment Work Gloves",
    "seoFilename": "safety-equipment-work-gloves-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\fire-safety\\fire-safety-emergency-light-1-almazahir.webp": {
    "alt": "Safety Emergency Light 1 - Fire & Safety by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Safety Emergency Light 1 | Fire & Safety | Al Mazahir Trading Est.",
    "description": "High-quality safety emergency light 1 available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Fire prevention and emergency safety systems.",
    "keywords": [
      "Safety Emergency Light 1",
      "fire safety",
      "emergency",
      "fire prevention",
      "Saudi Arabia",
      "industrial",
      "Al Mazahir Trading Est."
    ],
    "category": "fire-safety",
    "productName": "Safety Emergency Light 1",
    "seoFilename": "fire-safety-emergency-light-1-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\fire-safety\\fire-safety-emergency-light-almazahir.webp": {
    "alt": "Safety Emergency Light - Fire & Safety by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Safety Emergency Light | Fire & Safety | Al Mazahir Trading Est.",
    "description": "High-quality safety emergency light available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Fire prevention and emergency safety systems.",
    "keywords": [
      "Safety Emergency Light",
      "fire safety",
      "emergency",
      "fire prevention",
      "Saudi Arabia",
      "industrial",
      "Al Mazahir Trading Est."
    ],
    "category": "fire-safety",
    "productName": "Safety Emergency Light",
    "seoFilename": "fire-safety-emergency-light-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\fire-safety\\fire-safety-fire-blanket-1-almazahir.webp": {
    "alt": "Safety Fire Blanket 1 - Fire & Safety by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Safety Fire Blanket 1 | Fire & Safety | Al Mazahir Trading Est.",
    "description": "High-quality safety fire blanket 1 available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Fire prevention and emergency safety systems.",
    "keywords": [
      "Safety Fire Blanket 1",
      "fire safety",
      "emergency",
      "fire prevention",
      "Saudi Arabia",
      "industrial",
      "Al Mazahir Trading Est."
    ],
    "category": "fire-safety",
    "productName": "Safety Fire Blanket 1",
    "seoFilename": "fire-safety-fire-blanket-1-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\fire-safety\\fire-safety-fire-blanket-almazahir.webp": {
    "alt": "Safety Fire Blanket - Fire & Safety by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Safety Fire Blanket | Fire & Safety | Al Mazahir Trading Est.",
    "description": "High-quality safety fire blanket available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Fire prevention and emergency safety systems.",
    "keywords": [
      "Safety Fire Blanket",
      "fire safety",
      "emergency",
      "fire prevention",
      "Saudi Arabia",
      "industrial",
      "Al Mazahir Trading Est."
    ],
    "category": "fire-safety",
    "productName": "Safety Fire Blanket",
    "seoFilename": "fire-safety-fire-blanket-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\fire-safety\\fire-safety-fire-extinguisher-1-almazahir.webp": {
    "alt": "Safety Fire Extinguisher 1 - Fire & Safety by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Safety Fire Extinguisher 1 | Fire & Safety | Al Mazahir Trading Est.",
    "description": "High-quality safety fire extinguisher 1 available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Fire prevention and emergency safety systems.",
    "keywords": [
      "Safety Fire Extinguisher 1",
      "fire safety",
      "emergency",
      "fire prevention",
      "Saudi Arabia",
      "industrial",
      "Al Mazahir Trading Est."
    ],
    "category": "fire-safety",
    "productName": "Safety Fire Extinguisher 1",
    "seoFilename": "fire-safety-fire-extinguisher-1-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\fire-safety\\fire-safety-fire-extinguisher-almazahir.webp": {
    "alt": "Safety Fire Extinguisher - Fire & Safety by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Safety Fire Extinguisher | Fire & Safety | Al Mazahir Trading Est.",
    "description": "High-quality safety fire extinguisher available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Fire prevention and emergency safety systems.",
    "keywords": [
      "Safety Fire Extinguisher",
      "fire safety",
      "emergency",
      "fire prevention",
      "Saudi Arabia",
      "industrial",
      "Al Mazahir Trading Est."
    ],
    "category": "fire-safety",
    "productName": "Safety Fire Extinguisher",
    "seoFilename": "fire-safety-fire-extinguisher-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\fire-safety\\fire-safety-fire-safety-almazahir.webp": {
    "alt": "Safety Fire Safety - Fire & Safety by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Safety Fire Safety | Fire & Safety | Al Mazahir Trading Est.",
    "description": "High-quality safety fire safety available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Fire prevention and emergency safety systems.",
    "keywords": [
      "Safety Fire Safety",
      "fire safety",
      "emergency",
      "fire prevention",
      "Saudi Arabia",
      "industrial",
      "Al Mazahir Trading Est."
    ],
    "category": "fire-safety",
    "productName": "Safety Fire Safety",
    "seoFilename": "fire-safety-fire-safety-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\fire-safety\\fire-safety-smoke-detector-1-almazahir.webp": {
    "alt": "Safety Smoke Detector 1 - Fire & Safety by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Safety Smoke Detector 1 | Fire & Safety | Al Mazahir Trading Est.",
    "description": "High-quality safety smoke detector 1 available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Fire prevention and emergency safety systems.",
    "keywords": [
      "Safety Smoke Detector 1",
      "fire safety",
      "emergency",
      "fire prevention",
      "Saudi Arabia",
      "industrial",
      "Al Mazahir Trading Est."
    ],
    "category": "fire-safety",
    "productName": "Safety Smoke Detector 1",
    "seoFilename": "fire-safety-smoke-detector-1-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\fire-safety\\fire-safety-smoke-detector-almazahir.webp": {
    "alt": "Safety Smoke Detector - Fire & Safety by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Safety Smoke Detector | Fire & Safety | Al Mazahir Trading Est.",
    "description": "High-quality safety smoke detector available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Fire prevention and emergency safety systems.",
    "keywords": [
      "Safety Smoke Detector",
      "fire safety",
      "emergency",
      "fire prevention",
      "Saudi Arabia",
      "industrial",
      "Al Mazahir Trading Est."
    ],
    "category": "fire-safety",
    "productName": "Safety Smoke Detector",
    "seoFilename": "fire-safety-smoke-detector-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\tools-machinery\\tools-machinery-angle-grinder-1-almazahir.webp": {
    "alt": "Machinery Angle Grinder 1 - Tools & Machinery by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Machinery Angle Grinder 1 | Tools & Machinery | Al Mazahir Trading Est.",
    "description": "High-quality machinery angle grinder 1 available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Professional tools and industrial machinery.",
    "keywords": [
      "Machinery Angle Grinder 1",
      "tools",
      "machinery",
      "industrial equipment",
      "Saudi Arabia",
      "construction",
      "Al Mazahir Trading Est."
    ],
    "category": "tools-machinery",
    "productName": "Machinery Angle Grinder 1",
    "seoFilename": "tools-machinery-angle-grinder-1-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\tools-machinery\\tools-machinery-angle-grinder-almazahir.webp": {
    "alt": "Machinery Angle Grinder - Tools & Machinery by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Machinery Angle Grinder | Tools & Machinery | Al Mazahir Trading Est.",
    "description": "High-quality machinery angle grinder available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Professional tools and industrial machinery.",
    "keywords": [
      "Machinery Angle Grinder",
      "tools",
      "machinery",
      "industrial equipment",
      "Saudi Arabia",
      "construction",
      "Al Mazahir Trading Est."
    ],
    "category": "tools-machinery",
    "productName": "Machinery Angle Grinder",
    "seoFilename": "tools-machinery-angle-grinder-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\tools-machinery\\tools-machinery-compressor-almazahir.webp": {
    "alt": "Machinery Compressor - Tools & Machinery by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Machinery Compressor | Tools & Machinery | Al Mazahir Trading Est.",
    "description": "High-quality machinery compressor available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Professional tools and industrial machinery.",
    "keywords": [
      "Machinery Compressor",
      "tools",
      "machinery",
      "industrial equipment",
      "Saudi Arabia",
      "construction",
      "Al Mazahir Trading Est."
    ],
    "category": "tools-machinery",
    "productName": "Machinery Compressor",
    "seoFilename": "tools-machinery-compressor-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\tools-machinery\\tools-machinery-power-drill-1-almazahir.webp": {
    "alt": "Machinery Power Drill 1 - Tools & Machinery by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Machinery Power Drill 1 | Tools & Machinery | Al Mazahir Trading Est.",
    "description": "High-quality machinery power drill 1 available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Professional tools and industrial machinery.",
    "keywords": [
      "Machinery Power Drill 1",
      "tools",
      "machinery",
      "industrial equipment",
      "Saudi Arabia",
      "construction",
      "Al Mazahir Trading Est."
    ],
    "category": "tools-machinery",
    "productName": "Machinery Power Drill 1",
    "seoFilename": "tools-machinery-power-drill-1-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\tools-machinery\\tools-machinery-power-drill-almazahir.webp": {
    "alt": "Machinery Power Drill - Tools & Machinery by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Machinery Power Drill | Tools & Machinery | Al Mazahir Trading Est.",
    "description": "High-quality machinery power drill available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Professional tools and industrial machinery.",
    "keywords": [
      "Machinery Power Drill",
      "tools",
      "machinery",
      "industrial equipment",
      "Saudi Arabia",
      "construction",
      "Al Mazahir Trading Est."
    ],
    "category": "tools-machinery",
    "productName": "Machinery Power Drill",
    "seoFilename": "tools-machinery-power-drill-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\tools-machinery\\tools-machinery-safety-equipment-almazahir.webp": {
    "alt": "Machinery Safety Equipment - Tools & Machinery by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Machinery Safety Equipment | Tools & Machinery | Al Mazahir Trading Est.",
    "description": "High-quality machinery safety equipment available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Professional tools and industrial machinery.",
    "keywords": [
      "Machinery Safety Equipment",
      "tools",
      "machinery",
      "industrial equipment",
      "Saudi Arabia",
      "construction",
      "Al Mazahir Trading Est."
    ],
    "category": "tools-machinery",
    "productName": "Machinery Safety Equipment",
    "seoFilename": "tools-machinery-safety-equipment-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\tools-machinery\\tools-machinery-tools-machinery-almazahir.webp": {
    "alt": "Machinery Tools Machinery - Tools & Machinery by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Machinery Tools Machinery | Tools & Machinery | Al Mazahir Trading Est.",
    "description": "High-quality machinery tools machinery available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Professional tools and industrial machinery.",
    "keywords": [
      "Machinery Tools Machinery",
      "tools",
      "machinery",
      "industrial equipment",
      "Saudi Arabia",
      "construction",
      "Al Mazahir Trading Est."
    ],
    "category": "tools-machinery",
    "productName": "Machinery Tools Machinery",
    "seoFilename": "tools-machinery-tools-machinery-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\tools-machinery\\tools-machinery-welding-machine-1-almazahir.webp": {
    "alt": "Machinery Welding Machine 1 - Tools & Machinery by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Machinery Welding Machine 1 | Tools & Machinery | Al Mazahir Trading Est.",
    "description": "High-quality machinery welding machine 1 available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Professional tools and industrial machinery.",
    "keywords": [
      "Machinery Welding Machine 1",
      "tools",
      "machinery",
      "industrial equipment",
      "Saudi Arabia",
      "construction",
      "Al Mazahir Trading Est."
    ],
    "category": "tools-machinery",
    "productName": "Machinery Welding Machine 1",
    "seoFilename": "tools-machinery-welding-machine-1-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\tools-machinery\\tools-machinery-welding-machine-almazahir.webp": {
    "alt": "Machinery Welding Machine - Tools & Machinery by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Machinery Welding Machine | Tools & Machinery | Al Mazahir Trading Est.",
    "description": "High-quality machinery welding machine available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Professional tools and industrial machinery.",
    "keywords": [
      "Machinery Welding Machine",
      "tools",
      "machinery",
      "industrial equipment",
      "Saudi Arabia",
      "construction",
      "Al Mazahir Trading Est."
    ],
    "category": "tools-machinery",
    "productName": "Machinery Welding Machine",
    "seoFilename": "tools-machinery-welding-machine-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\construction-materials\\construction-materials-cement-bags-almazahir.webp": {
    "alt": "Materials Cement Bags - Construction Materials by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Materials Cement Bags | Construction Materials | Al Mazahir Trading Est.",
    "description": "High-quality materials cement bags available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Quality building and construction materials.",
    "keywords": [
      "Materials Cement Bags",
      "construction",
      "building materials",
      "cement",
      "steel",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "construction-materials",
    "productName": "Materials Cement Bags",
    "seoFilename": "construction-materials-cement-bags-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\construction-materials\\construction-materials-concrete-blocks-1-almazahir.webp": {
    "alt": "Materials Concrete Blocks 1 - Construction Materials by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Materials Concrete Blocks 1 | Construction Materials | Al Mazahir Trading Est.",
    "description": "High-quality materials concrete blocks 1 available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Quality building and construction materials.",
    "keywords": [
      "Materials Concrete Blocks 1",
      "construction",
      "building materials",
      "cement",
      "steel",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "construction-materials",
    "productName": "Materials Concrete Blocks 1",
    "seoFilename": "construction-materials-concrete-blocks-1-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\construction-materials\\construction-materials-concrete-blocks-almazahir.webp": {
    "alt": "Materials Concrete Blocks - Construction Materials by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Materials Concrete Blocks | Construction Materials | Al Mazahir Trading Est.",
    "description": "High-quality materials concrete blocks available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Quality building and construction materials.",
    "keywords": [
      "Materials Concrete Blocks",
      "construction",
      "building materials",
      "cement",
      "steel",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "construction-materials",
    "productName": "Materials Concrete Blocks",
    "seoFilename": "construction-materials-concrete-blocks-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\construction-materials\\construction-materials-portland-cement-almazahir.webp": {
    "alt": "Materials Portland Cement - Construction Materials by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Materials Portland Cement | Construction Materials | Al Mazahir Trading Est.",
    "description": "High-quality materials portland cement available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Quality building and construction materials.",
    "keywords": [
      "Materials Portland Cement",
      "construction",
      "building materials",
      "cement",
      "steel",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "construction-materials",
    "productName": "Materials Portland Cement",
    "seoFilename": "construction-materials-portland-cement-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\construction-materials\\construction-materials-steel-rebar-1-almazahir.webp": {
    "alt": "Materials Steel Rebar 1 - Construction Materials by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Materials Steel Rebar 1 | Construction Materials | Al Mazahir Trading Est.",
    "description": "High-quality materials steel rebar 1 available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Quality building and construction materials.",
    "keywords": [
      "Materials Steel Rebar 1",
      "construction",
      "building materials",
      "cement",
      "steel",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "construction-materials",
    "productName": "Materials Steel Rebar 1",
    "seoFilename": "construction-materials-steel-rebar-1-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\construction-materials\\construction-materials-steel-rebar-almazahir.webp": {
    "alt": "Materials Steel Rebar - Construction Materials by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Materials Steel Rebar | Construction Materials | Al Mazahir Trading Est.",
    "description": "High-quality materials steel rebar available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Quality building and construction materials.",
    "keywords": [
      "Materials Steel Rebar",
      "construction",
      "building materials",
      "cement",
      "steel",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "construction-materials",
    "productName": "Materials Steel Rebar",
    "seoFilename": "construction-materials-steel-rebar-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\industrial-supplies\\industrial-supplies-chemicals-almazahir.webp": {
    "alt": "Supplies Chemicals - Industrial Supplies by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Supplies Chemicals | Industrial Supplies | Al Mazahir Trading Est.",
    "description": "High-quality supplies chemicals available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Essential industrial supplies and maintenance materials.",
    "keywords": [
      "Supplies Chemicals",
      "industrial supplies",
      "maintenance",
      "chemicals",
      "fasteners",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "industrial-supplies",
    "productName": "Supplies Chemicals",
    "seoFilename": "industrial-supplies-chemicals-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\industrial-supplies\\industrial-supplies-fasteners-1-almazahir.webp": {
    "alt": "Supplies Fasteners 1 - Industrial Supplies by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Supplies Fasteners 1 | Industrial Supplies | Al Mazahir Trading Est.",
    "description": "High-quality supplies fasteners 1 available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Essential industrial supplies and maintenance materials.",
    "keywords": [
      "Supplies Fasteners 1",
      "industrial supplies",
      "maintenance",
      "chemicals",
      "fasteners",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "industrial-supplies",
    "productName": "Supplies Fasteners 1",
    "seoFilename": "industrial-supplies-fasteners-1-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\industrial-supplies\\industrial-supplies-fasteners-almazahir.webp": {
    "alt": "Supplies Fasteners - Industrial Supplies by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Supplies Fasteners | Industrial Supplies | Al Mazahir Trading Est.",
    "description": "High-quality supplies fasteners available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Essential industrial supplies and maintenance materials.",
    "keywords": [
      "Supplies Fasteners",
      "industrial supplies",
      "maintenance",
      "chemicals",
      "fasteners",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "industrial-supplies",
    "productName": "Supplies Fasteners",
    "seoFilename": "industrial-supplies-fasteners-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\industrial-supplies\\industrial-supplies-industrial-adhesive-1-almazahir.webp": {
    "alt": "Supplies Industrial Adhesive 1 - Industrial Supplies by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Supplies Industrial Adhesive 1 | Industrial Supplies | Al Mazahir Trading Est.",
    "description": "High-quality supplies industrial adhesive 1 available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Essential industrial supplies and maintenance materials.",
    "keywords": [
      "Supplies Industrial Adhesive 1",
      "industrial supplies",
      "maintenance",
      "chemicals",
      "fasteners",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "industrial-supplies",
    "productName": "Supplies Industrial Adhesive 1",
    "seoFilename": "industrial-supplies-industrial-adhesive-1-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\industrial-supplies\\industrial-supplies-industrial-adhesive-almazahir.webp": {
    "alt": "Supplies Industrial Adhesive - Industrial Supplies by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Supplies Industrial Adhesive | Industrial Supplies | Al Mazahir Trading Est.",
    "description": "High-quality supplies industrial adhesive available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Essential industrial supplies and maintenance materials.",
    "keywords": [
      "Supplies Industrial Adhesive",
      "industrial supplies",
      "maintenance",
      "chemicals",
      "fasteners",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "industrial-supplies",
    "productName": "Supplies Industrial Adhesive",
    "seoFilename": "industrial-supplies-industrial-adhesive-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\industrial-supplies\\industrial-supplies-lubricant-almazahir.webp": {
    "alt": "Supplies Lubricant - Industrial Supplies by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Supplies Lubricant | Industrial Supplies | Al Mazahir Trading Est.",
    "description": "High-quality supplies lubricant available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Essential industrial supplies and maintenance materials.",
    "keywords": [
      "Supplies Lubricant",
      "industrial supplies",
      "maintenance",
      "chemicals",
      "fasteners",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "industrial-supplies",
    "productName": "Supplies Lubricant",
    "seoFilename": "industrial-supplies-lubricant-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\industrial-supplies\\industrial-supplies-lubricants-almazahir.webp": {
    "alt": "Supplies Lubricants - Industrial Supplies by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Supplies Lubricants | Industrial Supplies | Al Mazahir Trading Est.",
    "description": "High-quality supplies lubricants available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Essential industrial supplies and maintenance materials.",
    "keywords": [
      "Supplies Lubricants",
      "industrial supplies",
      "maintenance",
      "chemicals",
      "fasteners",
      "Saudi Arabia",
      "Al Mazahir Trading Est."
    ],
    "category": "industrial-supplies",
    "productName": "Supplies Lubricants",
    "seoFilename": "industrial-supplies-lubricants-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\rental-equipment\\rental-equipment-forklift-almazahir.webp": {
    "alt": "Equipment Forklift - Rental Equipment by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Equipment Forklift | Rental Equipment | Al Mazahir Trading Est.",
    "description": "High-quality equipment forklift available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Heavy equipment rental and logistics solutions.",
    "keywords": [
      "Equipment Forklift",
      "equipment rental",
      "heavy machinery",
      "logistics",
      "Saudi Arabia",
      "construction",
      "Al Mazahir Trading Est."
    ],
    "category": "rental-equipment",
    "productName": "Equipment Forklift",
    "seoFilename": "rental-equipment-forklift-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\rental-equipment\\rental-equipment-forklift-rental-almazahir.webp": {
    "alt": "Equipment Forklift Rental - Rental Equipment by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Equipment Forklift Rental | Rental Equipment | Al Mazahir Trading Est.",
    "description": "High-quality equipment forklift rental available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Heavy equipment rental and logistics solutions.",
    "keywords": [
      "Equipment Forklift Rental",
      "equipment rental",
      "heavy machinery",
      "logistics",
      "Saudi Arabia",
      "construction",
      "Al Mazahir Trading Est."
    ],
    "category": "rental-equipment",
    "productName": "Equipment Forklift Rental",
    "seoFilename": "rental-equipment-forklift-rental-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\rental-equipment\\rental-equipment-mobile-crane-almazahir.webp": {
    "alt": "Equipment Mobile Crane - Rental Equipment by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Equipment Mobile Crane | Rental Equipment | Al Mazahir Trading Est.",
    "description": "High-quality equipment mobile crane available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Heavy equipment rental and logistics solutions.",
    "keywords": [
      "Equipment Mobile Crane",
      "equipment rental",
      "heavy machinery",
      "logistics",
      "Saudi Arabia",
      "construction",
      "Al Mazahir Trading Est."
    ],
    "category": "rental-equipment",
    "productName": "Equipment Mobile Crane",
    "seoFilename": "rental-equipment-mobile-crane-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\rental-equipment\\rental-equipment-rental-logistics-almazahir.webp": {
    "alt": "Equipment Rental Logistics - Rental Equipment by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Equipment Rental Logistics | Rental Equipment | Al Mazahir Trading Est.",
    "description": "High-quality equipment rental logistics available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Heavy equipment rental and logistics solutions.",
    "keywords": [
      "Equipment Rental Logistics",
      "equipment rental",
      "heavy machinery",
      "logistics",
      "Saudi Arabia",
      "construction",
      "Al Mazahir Trading Est."
    ],
    "category": "rental-equipment",
    "productName": "Equipment Rental Logistics",
    "seoFilename": "rental-equipment-rental-logistics-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\rental-equipment\\rental-equipment-scaffolding-1-almazahir.webp": {
    "alt": "Equipment Scaffolding 1 - Rental Equipment by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Equipment Scaffolding 1 | Rental Equipment | Al Mazahir Trading Est.",
    "description": "High-quality equipment scaffolding 1 available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Heavy equipment rental and logistics solutions.",
    "keywords": [
      "Equipment Scaffolding 1",
      "equipment rental",
      "heavy machinery",
      "logistics",
      "Saudi Arabia",
      "construction",
      "Al Mazahir Trading Est."
    ],
    "category": "rental-equipment",
    "productName": "Equipment Scaffolding 1",
    "seoFilename": "rental-equipment-scaffolding-1-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  },
  "public\\assets\\rental-equipment\\rental-equipment-scaffolding-almazahir.webp": {
    "alt": "Equipment Scaffolding - Rental Equipment by Al Mazahir Trading Est., Saudi Arabia",
    "title": "Equipment Scaffolding | Rental Equipment | Al Mazahir Trading Est.",
    "description": "High-quality equipment scaffolding available from Al Mazahir Trading Est., leading industrial supplier in Saudi Arabia. Heavy equipment rental and logistics solutions.",
    "keywords": [
      "Equipment Scaffolding",
      "equipment rental",
      "heavy machinery",
      "logistics",
      "Saudi Arabia",
      "construction",
      "Al Mazahir Trading Est."
    ],
    "category": "rental-equipment",
    "productName": "Equipment Scaffolding",
    "seoFilename": "rental-equipment-scaffolding-almazahir.webp",
    "dimensions": "Optimized for web (max 1920px)",
    "format": "WebP",
    "quality": "High (85%)",
    "accessibility": {
      "hasAltText": true,
      "hasTitle": true,
      "isDescriptive": true,
      "includesContext": true
    }
  }
};

/**
 * Helper function to get metadata for an image path
 */
export function getImageMetadata(imagePath: string): ImageMetadata | null {
  // Try the path as-is first
  let metadata = imageMetadata[imagePath];
  if (metadata) return metadata;
  
  // Try converting forward slashes to backslashes (Windows style)
  const windowsPath = imagePath.replace(/\//g, '\\');
  metadata = imageMetadata[windowsPath];
  if (metadata) return metadata;
  
  // Try with 'public' prefix and backslashes
  const publicWindowsPath = `public${windowsPath}`;
  metadata = imageMetadata[publicWindowsPath];
  if (metadata) return metadata;
  
  // Try with 'public' prefix and forward slashes
  const publicPath = `public${imagePath}`;
  metadata = imageMetadata[publicPath];
  if (metadata) return metadata;
  
  return null;
}

/**
 * Helper function to get alt text for an image
 */
export function getImageAlt(imagePath: string): string {
  const metadata = getImageMetadata(imagePath);
  return metadata?.alt || 'Al Mazahir Trading Est. product image';
}

/**
 * Helper function to get title for an image
 */
export function getImageTitle(imagePath: string): string {
  const metadata = getImageMetadata(imagePath);
  return metadata?.title || 'Al Mazahir Trading Est. - Industrial Supplier Saudi Arabia';
}
